---
apiVersion: v1
kind: Pod 
metadata: 
  name: busybox-worker1
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec: 
  containers: 
  - image: busybox
    command:
      - sleep 
      - "3600"
    imagePullPolicy: IfNotPresent 
    name: busybox 
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1
  restartPolicy: Always 
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-worker2
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    kubernetes.io/hostname: k8s-worker2
  restartPolicy: Always
---
