---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpbin-0
  labels:
   postnum: "0"
   app: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
      postnum: "0"
  replicas: 1 
  template:
    metadata:
      labels:
        app: httpbin
        postnum: "0"
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpbin-1
  labels:
   postnum: "1"
   app: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
      postnum: "1"
  replicas: 1 
  template:
    metadata:
      labels:
        app: httpbin
        postnum: "1"
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  sessionAffinity: ClientIP
  type: ClusterIP
---
