apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: mariadb-pool
  namespace: rook-ceph
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-ceph-block
provisioner: ceph.rook.io/block
parameters:
  blockPool: mariadb-pool
  clusterNamespace: rook-ceph
  fstype: xfs
---

