apiVersion: v1
kind: Pod
metadata:
  name: busybox-default-calico2
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/20-calico
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
