#cloud-config
---
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx7Yzec0R0mFIfERUdthHiOCi6M0Z8KWH1r8K4Mn8w/i7yWqoNn75T2JRNZie9vBkNZoQvvs+tIfA/vsoBHZbVCJSMJxykpIxMUtfoPrQga3gYKROzq1xVpEIAbeY6gbQZvAUqwQ6tBhNBESGNKm2iFzHC7P/ftH9thSuVxRuh3lEaH5eOP3/TfnQTbsQlE33z0v+NZXZnhkbBQaBOj5K4F/DqY/JxNFNl4bPElm0Jm/sHUwle91wVuvwSoCL1lCOoCVQaCbioaRUYYCAukn6lHYgkbPBzTfAtIBtQvps/dTl+Qc840J5PTiySdX7TnLjGZRqvmGfRiJg4ZL6+Usvf root@di7-03

systemd:
  units:
    - name: "coreos-metadata.service"
      dropins:
       - name: "use-script.conf"
         contents: |
          [Service]
          # Empty ExecStart= prevents the previously defined ExecStart from running
          ExecStart=
          ExecStart=/opt/get-metadata.sh
    - name: "etcd-member.service"
      dropins:
       - name: "10-provision.conf"
         contents: |
          [Unit]
          Description=EC2 metadata agent

          [Service]
          Type=oneshot
          Environment=OUTPUT=/run/metadata/coreos
          ExecStart=/usr/bin/mkdir --parent /run/metadata
          ExecStart=/usr/bin/bash -c 'echo "CUSTOM_IPV4_PRIVATE=192.168.122.2\nCUSTOM_IPV4_PUBLIC=192.168.122.2" > ${OUTPUT}'