#!/usr/bin/env bash 
set -uv

# remove old file 
rm -rf provision-disk-10G.qcow2  provision.xml

source source

qemu-img create -f $DISK_FORMAT -b $CDROM $NODE_NAME-disk-$DISK_SIZE.$DISK_FORMAT  $DISK_SIZE

virt-install \
    --connect qemu:///system \
    --import \
    --name $NODE_NAME \
    --ram $VRAM \
    --vcpus $VCPU \
    --os-type=$OSTYPE \
    --os-variant=$OSVARIANT \
    --disk $DISK \
    --network $NETWORK \
    --vnc --noautoconsole \
    --print-xml > $OUTPUT

sed -i 's|type="kvm"|type="kvm" xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0"|' "${OUTPUT}"
sed -i "/<\/devices>/a <qemu:commandline>\n  <qemu:arg value='-fw_cfg'/>\n  <qemu:arg value='name=opt/com.coreos/config,file=$IGNITION'/>\n</qemu:commandline>" "${OUTPUT}"

virsh define $OUTPUT && virsh start $NODE_NAME
