apiVersion: v1
kind: Pod 
metadata: 
  name: busybox-macvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec: 
  containers: 
  - image: busybox
    command:
      - sleep 
      - "3600"
    imagePullPolicy: IfNotPresent 
    name: busybox 
  restartPolicy: Always 
