---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: mongo-shard-pool
  namespace: rook-ceph
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-shard-block
parameters:
  blockPool: mongo-shard-pool
  clusterNamespace: rook-ceph
  fstype: xfs
provisioner: ceph.rook.io/block
reclaimPolicy: Delete
---

